### ISSUE TITLE
deprecated functions

### ISSUE THREAD

**Issue by fossfreedom** [donaghhorgan/rhythmbox-plugins-rating-filters#3]
whilst testing on fedora 18, the following terminal messages were observed:

![pic](http://i.imgur.com/fnqbNPD.png)

the use of set_data and get_data in the main py file will not work in later versions of pygobject.

**Comment by donaghhorgan** [comment]
Great, thanks again. I know what the problem is here, should be fixable relatively soonish...

**Comment by donaghhorgan** [comment]
I never tested on 2.98 (went from 2.97 to 2.99 directly), so this one slipped through the net. I've added a new version for 2.98 and bumped the old one to 2.97 and below, so it should be error free now. I've tested the plugin on 2.96-2.99 and there doesn't seem to be anything else I missed, thankfully.

Now, I must go check my other plugins because I suspect the same bug is affecting them...

**Comment by fossfreedom** [comment]
Yep - that works - excellent!
